### PR TITLE
feat(enable button): EditView is hidden if url alias is not enabled

### PR DESCRIPTION
**Pull request by Alexnortung**
### What does it do?

If a content type has disabled url alias it will no longer show the url alias edit view in the content manager

### Why is it needed?

Less clutter on the page, which gives a better user experience

### How to test it?

Try disabling url alias for one of your content types and check in the content manager that it is longer there

### Related issue(s)/PR(s)

#38

### CODE REVIEW

**Review by boazpoolman — CHANGES_REQUESTED** [review]
I think the extra `/info/getPluginOptions` endpoint is a bit overkill.
We might be better of just altering the existing `/info/getContentTypes` endpoint to only return the content types that have `url-alias` enabled.

We can change the logic here to make that happend:
https://github.com/strapi-community/strapi-plugin-url-alias/blob/master/server/admin-api/controllers/info.ts#L22

That way you are also only able to create a URL pattern for a content type that has `url-alias` enabled. Which is a nice side effect.

**Comment by Alexnortung** [comment]
Sounds like a great solution, I will definitely do that :D

**Comment by Alexnortung** [comment]
I have implemented it now

The patternview will now also use the same hook, so that the data is cached and doesn't need to be refetched

**Comment by Alexnortung** [comment]
I have also made sure that `url_path_id` is removed, this will give better performance and this is also important because it could cause issues with #33 where users would not be able to get around the error at all.

**Review by boazpoolman — APPROVED** [review]
LGTM

**Pull request merged**
