### PR TITLE
Feature/drop node 16

### PR DESCRIPTION
**Pull request by MSACC**
### What does it do?

Drop node 16 support

### Why is it needed?

Because Strapi will drop node 16 support starting `v1.14.5`

### How to test it?

Just make sure the tests are successful.

### Related issue(s)/PR(s)

None

### CODE REVIEW

**Comment by boazpoolman** [comment]
Hi @Alexnortung 

Do you by any chance know why these tests are failing?
We're upgrading to the latest version of all the `@strapi` packages and we seem to be getting some Typescript issues.
I know Strapi has worked hard lately at implementing better types for their APIs but I can't seem to properly fix these issues locally.

**Comment by Alexnortung** [comment]
I am not sure right now. One of the errors is that it cannot find transformResponse, so we should probably figure out where they are exporting that function now.

I am not sure about the type errors in the getPluginService function, but I can take a look at it tomorrow or Monday :)

I guess we could try to use `as any` where the string is supplied instead of `ContentType`, since we of course do not have the content types of the user's environment.

**Comment by Alexnortung** [comment]
I fixed some of the type erros on a local branch but I cannot push to this pull request as there are some protection rules. Could you take a look at that @boazpoolman?

```
$ git push community drop-node-16:pull/58/head
Enumerating objects: 41, done.
Counting objects: 100% (41/41), done.
Delta compression using up to 20 threads
Compressing objects: 100% (28/28), done.
Writing objects: 100% (29/29), 18.95 KiB | 2.71 MiB/s, done.
Total 29 (delta 20), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (20/20), completed with 10 local objects.
remote: error: GH013: Repository rule violations found for refs/heads/pull/58/head.
remote: Review all repository rules at http://github.com/strapi-community/strapi-plugin-url-alias/rules?ref=refs%2Fheads%2Fpull%2F58%2Fhead
remote:
remote: - 2 of 2 required status checks are expected.
remote:
To github.com:strapi-community/strapi-plugin-url-alias.git
 ! [remote rejected] drop-node-16 -> pull/58/head (push declined due to repository rule violations)
error: failed to push some refs to 'github.com:strapi-community/strapi-plugin-url-alias.git'
```

**Comment by boazpoolman** [comment]
Look at this gist to see how to contribute to a foreigh fork https://gist.github.com/wtbarnes/56b942641d314522094d312bbaf33a81

**Comment by boazpoolman** [comment]
Hi @Alexnortung,

I’ve updated the protection rules.
Could you try pushing your changes again?

**Comment by Alexnortung** [comment]
Alright I have pushed them now, there are still one issue, but I am not entirely sure how it works and it could probably be refactored a bit. But it is in the `override-query-layer` file the last issue is.

**Comment by boazpoolman** [comment]
Thanks for your help @Alexnortung

That last typescript issue in the override-query-layer file I've `@ts-ignore`'d.
I'm in the progress of removing that file in PR #56 anyways, so just ignoring the issue for now should be fine.

**Review by boazpoolman — APPROVED** [review]

**Pull request merged**
