### PR TITLE
Feature/migration

### PR DESCRIPTION
**Pull request by boazpoolman**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by Alexnortung** [comment]
Hey Boaz, I am not really sure how to set up the monorepo locally. I have tried installing dependencies and running `yarn run build` and changing the `resolve` path for the plugin, but it doesn't seem to work properly.

```ts
// config/plugins.ts
  "url-alias": {
    enabled: true,
    resolve: "./src/plugins/strapi-plugin-url-alias/packages/core/",
  },
```

And when I try to build the package from the folder itself it is giving me an error since it cannot find `tsc` anymore.

**Comment by boazpoolman** [comment]
Hey Alex.
I have yet to write a `CONTRIBUTING.md` but the workflow is very similar to how I've setup the `strapi-plugin-sitemap`.
You could try and follow the contributing docs of that plugin, see https://github.com/boazpoolman/strapi-plugin-sitemap/blob/master/CONTRIBUTING.md.

The biggest change is the usage of the `playground`. That is a Strapi instance which is included in the repo. All the local development, testing etc will be done using that instance. That means if you do a `yarn run build` from the root of the repo it will build the different plugins into that Strapi instance. Afterwards you can start that instance by running `yarn playground:develop`.

Let me know if that works out :)

**Comment by Alexnortung** [comment]
Thanks Boaz, this works! I did also want to test it with an existing project, is that possible in any way without needing to copy all the files to the playground folder? :)

**Comment by boazpoolman** [comment]
I haven't tested it myself, but whenever you do a `yarn run build` or `yarn run develop` the plugins will be built to this directory `playground/src/plugins`. You could just copy those folders and place them in your existing project. Would that work?

**Comment by Alexnortung** [comment]
I had a little issue with config-sync in my project (it may use an old version). The migration worked as expected :)

I think we could include a small note about changing the `config/plugins.ts` file from
```ts
  "url-alias": {
    enabled: true,
  },
```

to

```ts
  "webtools": {
    enabled: true,
  },
```

I also have another small change that I will commit :)

**Comment by Alexnortung** [comment]
I just realized that the other packages has the `strapi.d.ts` file in another location, should we change the location in the core plugin or the other plugins?

**Comment by boazpoolman** [comment]
@Alexnortung I don't know why, but [your commit](https://github.com/strapi-community/strapi-plugin-url-alias/pull/67/commits/085c4453e5751854acbade62db6b724b0cccd557) caused the build to fail on Typescript issues in weird places. See the pipeline output: https://github.com/strapi-community/strapi-plugin-url-alias/actions/runs/7142616514/job/19452273879#step:5:24

I've reverted the commit for now. We have to check later if we can make that work.

**Pull request merged**
